# Generated by Django 6.0.1 on 2026-01-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="products",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(related_name="products", to="api.tag"),
        ),
    ]
